### ISSUE TITLE
misa.pl for perl 5.26 or greater

### ISSUE THREAD

**Issue by marieBvr** [mnenno/PySSRstat#1]
Hi,
I would like to report that to make misa.pl works with perl 5.26 I had to modify the script on line 113:
from       ` my $redmotif = "([ACGT]{$j})\\1{".($motiflen/$j-1)."}";`
to      `  my $redmotif = "([ACGT]{$j})\\1\\{".($motiflen/$j-1)."}";`

Best regards
Marie

**Comment by mnenno** [comment]
Dear Marie,
thank you for your note. Given that misa.pl is a "third party" component which is not under my responsability I cannot change it.
However, I appreciate your message as an important note for all those that run misa.pl under Perl 5.26.

Thank you very much,
Mario
